version: '2.3'
services:
  chia-plotter:
    build:
      context: .
      dockerfile: Dockerfile
    image: compscidr/chia-plotter:dev
    container_name: chia-plotter
    volumes:
      - ~/.ssh:/home/plotuser/.ssh
