version: '2.3'
services:
  chia-plotter:
    build:
      context: .
      dockerfile: Dockerfile
    image: compscidr/chia-plotter:dev
    container_name: chia-plotter
    volumes:
      - ~/.ssh/id_rsa:/home/plotuser/.ssh/id_rsa
      - ~/.ssh/config:/home/plotuser/.ssh/config
