name: Deploy container
on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy container
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build image
        run: docker build -f Dockerfile -t chia-plotter-docker:${{ github.sha }} .
      - name: tag and push
        run: |
          docker tag chia-plotter-docker:${{ github.sha }} compscidr/chia-plotter-docker:${{ github.event.release.tag_name }}
          docker push compscidr/chia-plotter-docker:${{ github.event.release.tag_name }}
          docker tag chia-plotter-docker:${{ github.sha }} compscidr/chia-plotter-docker:latest
          docker push compscidr/chia-plotter-docker:latest
      - name: Logout of Docker Hub
        run: docker logout
